### ISSUE TITLE
Update AceStream bundle to v3.1.6

### ISSUE THREAD

**Issue by miltador** [aaaler/acestreamproxyvlc-pi#1]
Download link is here: http://www.4shared.com/zip/5SB6aS-kba/acestream-rpi2_v2.html

**Comment by aaaler** [comment]
`docker pull aaaler\acestream-pi:newest`
will push it into latest after few weeks of testing.

**Comment by aaaler** [comment]
some binaries in archive seems to be not executable, so new image do not work yet. Where(how) you made it ? if it's just unpacked .apk -- we should use latest version, i guess.

**Comment by aaaler** [comment]
new images avaliable on docker.io and seems to work:

-   `aaaler/acestream-pi:3.1.6`
-   `aaaler/acestream-pi:3.1.14.0`

please provide feedback on testing them
